ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy-m
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy-m/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy-m/sensor/io
obj-$(CONFIG_MSM_CCI) += msm_cci.o
