ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy-m
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy-m/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy-m/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy-m/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
