ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy-m
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy-m/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy-m/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy-m/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
